[package]
name = "gh-url-picker"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
octocrab = "0.44.0"
tokio = { version = "1.0", features = ["full"] }
ctrlc = "3.2"
termion = "4.0.5"
